### ISSUE TITLE
Use nginx to host static production files and handle the proxy

### ISSUE THREAD

**Issue by yqf3139** [fission/fission-ui#5]
Http-proxy-middleware is great for dev environment.
For production we can use use a nginx container to do the hosting and proxying.
For fission, provide a kubernetes yaml config.

**Comment by dgoujard** [comment]
Seems like a good idea !

**Comment by mingfang** [comment]
adding nginx does not bring much value but only to make things more complicated.

**Comment by yqf3139** [comment]
@mingfang 
Hi, we use node js server for dev and nginx for docker image.
We are glad if you want to contribute to build a nodejs server docker image.
